
model:
  name: openai/clip-vit-base-patch32

dataset:
  name: itsanmolgupta/mimic-cxr-dataset
  use_findings_if_missing: true
  root: /home/sysadm/Music/MedXpert/data/processed

training:
  batch_size: 8
  epochs: 50
  learning_rate: 5e-5
  save_path: models/clip/fine_tuned

embeddings:
  save_dir: data/embeddings

