model:
  name: openai/clip-vit-base-patch32

dataset:
  name: itsanmolgupta/mimic-cxr-dataset
  use_findings_if_missing: true

training:
  batch_size: 8
  epochs: 3
  learning_rate: 5e-5
  save_path: models/clip/fine_tuned

preprocessing:
  image_size: 224
  min_text_length: 10
